from django.core.management.base import BaseCommand, CommandError
from store.models import *
from datetime import date

class Command(BaseCommand):
    help = 'create all datas here'

    def handle(self, *args, **options):

        all_products = [
            {'name': 'Textbook', 'description': 'Versatile quality suitable everyday luxury stylish stylish suitable popular versatile eco-friendly portable quality modern essential long-lasting perfect high-performance luxury designed modern versatile comfortable versatile trendy.', 'category': 'Books & Stationery', 'price': 143, 'regular_price': 402, 'in_stock': 11},
            {'name': 'Chocolate', 'description': 'Versatile luxury perfect luxury comfortable professional exclusive comfortable exclusive trendy suitable reliable crafted professional high-performance compact innovative exclusive eco-friendly trendy innovative affordable compact.', 'category': 'Groceries & Food', 'price': 486, 'regular_price': 492, 'in_stock': 5},
            {'name': 'Sunglasses', 'description': 'Quality luxury everyday affordable perfect lightweight perfect lightweight long-lasting popular exclusive.', 'category': 'Clothing & Fashion', 'price': 154, 'regular_price': 470, 'in_stock': 15},
            {'name': 'Smartwatch', 'description': 'Versatile essential comfortable comfortable high-performance elegant portable premium elegant exclusive classic elegant compact crafted.', 'category': 'Electronics', 'price': 316, 'regular_price': 396, 'in_stock': 14},
            {'name': 'Cereal', 'description': 'Professional eco-friendly trendy versatile luxury portable essential versatile exclusive popular durable crafted popular essential affordable professional innovative crafted compact eco-friendly designed compact reliable.', 'category': 'Groceries & Food', 'price': 211, 'regular_price': 494, 'in_stock': 5},
            {'name': 'Car Vacuum', 'description': 'Trendy designed designed everyday reliable high-performance long-lasting elegant crafted perfect essential exclusive stylish durable stylish portable durable affordable quality compact popular premium versatile classic trendy unique comfortable professional affordable.', 'category': 'Automotive & Tools', 'price': 255, 'regular_price': 379, 'in_stock': 13},
            {'name': 'Tennis Racket', 'description': 'Compact long-lasting stylish durable compact portable versatile compact eco-friendly everyday professional portable reliable compact modern popular popular popular comfortable suitable elegant suitable high-performance reliable perfect durable stylish everyday elegant portable.', 'category': 'Sports & Fitness', 'price': 300, 'regular_price': 413, 'in_stock': 18},
            {'name': 'Shampoo', 'description': 'Durable essential innovative perfect crafted popular designed premium crafted essential long-lasting high-performance versatile essential modern versatile professional modern.', 'category': 'Health & Beauty', 'price': 276, 'regular_price': 310, 'in_stock': 15},
            {'name': 'Football', 'description': 'Modern unique classic versatile designed long-lasting reliable unique modern durable reliable eco-friendly long-lasting elegant perfect elegant essential.', 'category': 'Sports & Fitness', 'price': 100, 'regular_price': 238, 'in_stock': 9},
            {'name': 'Earrings', 'description': 'Stylish quality essential professional reliable long-lasting unique perfect elegant durable affordable unique luxury affordable innovative reliable.', 'category': 'Jewelry & Accessories', 'price': 161, 'regular_price': 284, 'in_stock': 18},
            {'name': 'Moisturizer', 'description': 'Unique reliable suitable luxury high-performance affordable stylish stylish perfect trendy portable versatile crafted quality modern exclusive premium portable.', 'category': 'Health & Beauty', 'price': 472, 'regular_price': 500, 'in_stock': 10},
            {'name': 'Moisturizer', 'description': 'Long-lasting elegant popular elegant trendy high-performance essential long-lasting popular luxury high-performance elegant high-performance reliable portable lightweight eco-friendly classic modern versatile unique.', 'category': 'Health & Beauty', 'price': 140, 'regular_price': 144, 'in_stock': 5},
            {'name': 'Tire Pump', 'description': 'Compact perfect suitable versatile popular unique luxury popular luxury versatile designed exclusive durable perfect elegant versatile exclusive designed stylish suitable portable.', 'category': 'Automotive & Tools', 'price': 172, 'regular_price': 260, 'in_stock': 14},
            {'name': 'Perfume', 'description': 'Everyday compact premium reliable innovative eco-friendly designed premium popular lightweight stylish modern classic luxury innovative versatile luxury essential eco-friendly trendy essential.', 'category': 'Health & Beauty', 'price': 488, 'regular_price': 499, 'in_stock': 8},
            {'name': 'Vacuum Cleaner', 'description': 'Quality stylish crafted essential professional quality luxury innovative compact lightweight crafted trendy classic trendy perfect compact premium perfect popular unique compact perfect compact modern durable everyday professional elegant innovative.', 'category': 'Home & Kitchen', 'price': 217, 'regular_price': 292, 'in_stock': 16},
            {'name': 'Blender', 'description': 'Crafted everyday popular trendy long-lasting exclusive professional portable high-performance premium trendy perfect.', 'category': 'Home & Kitchen', 'price': 238, 'regular_price': 291, 'in_stock': 20},
            {'name': 'Green Tea', 'description': 'Reliable reliable versatile eco-friendly lightweight elegant quality luxury modern elegant premium versatile modern quality long-lasting versatile suitable everyday durable modern exclusive modern luxury.', 'category': 'Groceries & Food', 'price': 323, 'regular_price': 444, 'in_stock': 10},
            {'name': 'Action Figure', 'description': 'Exclusive reliable durable affordable elegant essential crafted long-lasting exclusive popular designed stylish long-lasting crafted portable perfect eco-friendly long-lasting affordable eco-friendly unique affordable high-performance innovative suitable.', 'category': 'Toys & Games', 'price': 295, 'regular_price': 371, 'in_stock': 20},
            {'name': 'Dollhouse', 'description': 'Designed high-performance comfortable eco-friendly quality everyday quality trendy versatile classic portable innovative versatile affordable high-performance affordable durable modern exclusive stylish crafted portable elegant high-performance professional comfortable suitable suitable.', 'category': 'Toys & Games', 'price': 262, 'regular_price': 365, 'in_stock': 7},
            {'name': 'Action Figure', 'description': 'Versatile premium essential eco-friendly everyday portable compact high-performance everyday luxury designed designed eco-friendly essential affordable luxury unique modern trendy professional compact high-performance elegant.', 'category': 'Toys & Games', 'price': 435, 'regular_price': 490, 'in_stock': 16},
            {'name': 'Chocolate', 'description': 'Eco-friendly affordable durable durable stylish crafted unique compact professional long-lasting suitable portable innovative versatile trendy premium affordable essential trendy affordable.', 'category': 'Groceries & Food', 'price': 310, 'regular_price': 468, 'in_stock': 12},
            {'name': 'Tennis Racket', 'description': 'Luxury stylish exclusive popular luxury crafted classic compact unique perfect crafted trendy quality crafted durable.', 'category': 'Sports & Fitness', 'price': 194, 'regular_price': 331, 'in_stock': 19},
            {'name': 'Board Game', 'description': 'Elegant suitable innovative long-lasting suitable professional compact elegant durable versatile trendy long-lasting designed suitable affordable modern durable modern affordable comfortable unique exclusive crafted crafted innovative reliable affordable premium long-lasting everyday.', 'category': 'Toys & Games', 'price': 152, 'regular_price': 461, 'in_stock': 9},
            {'name': 'Smartwatch', 'description': 'Modern high-performance versatile lightweight trendy affordable portable perfect perfect popular durable popular affordable.', 'category': 'Electronics', 'price': 205, 'regular_price': 451, 'in_stock': 12},
            {'name': 'Coffee Maker', 'description': 'Lightweight long-lasting lightweight portable reliable premium long-lasting crafted durable lightweight popular essential unique stylish essential lightweight premium comfortable.', 'category': 'Home & Kitchen', 'price': 313, 'regular_price': 430, 'in_stock': 5},
            {'name': 'Non-stick Pan', 'description': 'Professional reliable comfortable innovative durable crafted exclusive affordable durable innovative everyday eco-friendly.', 'category': 'Home & Kitchen', 'price': 170, 'regular_price': 402, 'in_stock': 7},
            {'name': 'Green Tea', 'description': 'Popular essential suitable popular premium innovative durable eco-friendly comfortable versatile designed crafted trendy professional unique premium lightweight versatile perfect long-lasting crafted affordable designed.', 'category': 'Groceries & Food', 'price': 358, 'regular_price': 456, 'in_stock': 20},
            {'name': 'Blender', 'description': 'Perfect luxury crafted reliable essential innovative long-lasting stylish crafted affordable suitable lightweight elegant durable everyday essential everyday eco-friendly popular modern long-lasting everyday reliable comfortable durable exclusive classic modern essential premium.', 'category': 'Home & Kitchen', 'price': 206, 'regular_price': 391, 'in_stock': 17},
            {'name': 'Action Figure', 'description': 'Everyday unique unique perfect high-performance modern comfortable crafted luxury exclusive long-lasting eco-friendly everyday reliable.', 'category': 'Toys & Games', 'price': 305, 'regular_price': 393, 'in_stock': 17},
            {'name': 'Chocolate', 'description': 'Stylish modern quality unique long-lasting suitable comfortable portable suitable popular classic eco-friendly.', 'category': 'Groceries & Food', 'price': 470, 'regular_price': 482, 'in_stock': 7},
            {'name': 'Chocolate', 'description': 'Premium trendy classic luxury lightweight essential popular compact comfortable innovative premium affordable crafted luxury.', 'category': 'Groceries & Food', 'price': 262, 'regular_price': 263, 'in_stock': 12},
            {'name': 'Sunglasses', 'description': 'Versatile perfect portable unique crafted long-lasting crafted lightweight modern high-performance quality lightweight.', 'category': 'Clothing & Fashion', 'price': 294, 'regular_price': 462, 'in_stock': 14},
            {'name': 'Bracelet', 'description': 'Lightweight perfect long-lasting durable elegant long-lasting stylish portable stylish everyday classic essential professional exclusive premium exclusive professional modern eco-friendly modern unique modern lightweight long-lasting long-lasting trendy stylish suitable everyday popular.', 'category': 'Jewelry & Accessories', 'price': 455, 'regular_price': 494, 'in_stock': 10},
            {'name': 'Lipstick', 'description': 'Trendy affordable versatile trendy exclusive high-performance crafted popular crafted suitable high-performance everyday stylish lightweight professional lightweight suitable.', 'category': 'Health & Beauty', 'price': 438, 'regular_price': 449, 'in_stock': 10},
            {'name': 'Tennis Racket', 'description': 'Exclusive lightweight professional durable classic professional classic modern modern durable.', 'category': 'Sports & Fitness', 'price': 148, 'regular_price': 280, 'in_stock': 15},
            {'name': 'Planner', 'description': 'Innovative luxury high-performance affordable high-performance popular quality portable modern comfortable.', 'category': 'Books & Stationery', 'price': 279, 'regular_price': 410, 'in_stock': 17},
            {'name': 'Action Figure', 'description': 'Luxury exclusive classic everyday crafted long-lasting luxury popular versatile durable exclusive crafted high-performance premium exclusive affordable elegant unique crafted portable lightweight quality quality compact affordable.', 'category': 'Toys & Games', 'price': 419, 'regular_price': 441, 'in_stock': 12},
            {'name': 'Cereal', 'description': 'Innovative comfortable durable trendy quality professional innovative professional luxury exclusive premium premium lightweight affordable high-performance unique stylish perfect high-performance quality premium versatile durable popular luxury durable exclusive.', 'category': 'Groceries & Food', 'price': 369, 'regular_price': 493, 'in_stock': 12},
            {'name': 'Bracelet', 'description': 'Portable versatile long-lasting modern innovative luxury premium luxury designed essential comfortable modern luxury everyday innovative reliable exclusive exclusive innovative stylish stylish classic modern professional premium premium affordable durable exclusive.', 'category': 'Jewelry & Accessories', 'price': 299, 'regular_price': 362, 'in_stock': 17},
            {'name': 'Planner', 'description': 'Lightweight suitable compact popular popular durable elegant unique innovative modern luxury elegant suitable innovative suitable luxury eco-friendly.', 'category': 'Books & Stationery', 'price': 175, 'regular_price': 300, 'in_stock': 6},
            {'name': 'Novel', 'description': 'Unique everyday affordable modern luxury lightweight luxury compact suitable quality everyday high-performance modern reliable designed affordable reliable luxury trendy.', 'category': 'Books & Stationery', 'price': 133, 'regular_price': 340, 'in_stock': 15},
            {'name': 'Car Vacuum', 'description': 'Durable compact compact durable everyday luxury modern professional innovative lightweight luxury modern affordable professional designed innovative lightweight modern premium lightweight.', 'category': 'Automotive & Tools', 'price': 253, 'regular_price': 391, 'in_stock': 17},
            {'name': 'Perfume', 'description': 'Suitable affordable popular long-lasting modern long-lasting stylish trendy premium reliable long-lasting popular everyday suitable popular eco-friendly premium elegant everyday premium classic.', 'category': 'Health & Beauty', 'price': 102, 'regular_price': 346, 'in_stock': 20},
            {'name': 'Wireless Earbuds', 'description': 'Luxury classic quality long-lasting crafted trendy crafted long-lasting popular premium trendy lightweight professional high-performance elegant professional portable portable high-performance classic.', 'category': 'Electronics', 'price': 315, 'regular_price': 447, 'in_stock': 17},
            {'name': 'Moisturizer', 'description': 'Classic classic eco-friendly quality trendy durable classic modern suitable innovative long-lasting crafted durable exclusive designed popular compact.', 'category': 'Health & Beauty', 'price': 386, 'regular_price': 477, 'in_stock': 13},
            {'name': 'Vacuum Cleaner', 'description': 'Perfect modern popular innovative perfect modern affordable luxury perfect lightweight compact suitable durable perfect everyday reliable suitable.', 'category': 'Home & Kitchen', 'price': 215, 'regular_price': 366, 'in_stock': 12},
            {'name': 'Shampoo', 'description': 'Versatile versatile compact high-performance compact essential modern reliable suitable essential portable high-performance unique.', 'category': 'Health & Beauty', 'price': 210, 'regular_price': 255, 'in_stock': 18},
            {'name': 'Planner', 'description': 'Quality premium classic innovative crafted premium professional everyday unique essential luxury compact stylish exclusive versatile trendy luxury portable durable perfect perfect.', 'category': 'Books & Stationery', 'price': 284, 'regular_price': 415, 'in_stock': 9},
            {'name': 'Action Figure', 'description': 'Durable professional classic trendy elegant professional long-lasting reliable durable lightweight durable designed.', 'category': 'Toys & Games', 'price': 139, 'regular_price': 224, 'in_stock': 6},
            {'name': 'Jacket', 'description': 'Exclusive portable quality reliable premium affordable everyday popular essential modern everyday stylish essential durable high-performance versatile innovative exclusive.', 'category': 'Clothing & Fashion', 'price': 311, 'regular_price': 386, 'in_stock': 20},
            {'name': 'Smartwatch', 'description': 'Lightweight compact luxury essential trendy luxury eco-friendly elegant luxury designed luxury essential professional popular suitable designed trendy versatile.', 'category': 'Electronics', 'price': 110, 'regular_price': 309, 'in_stock': 17},
            {'name': 'Non-stick Pan', 'description': 'Lightweight crafted luxury perfect unique versatile innovative portable eco-friendly everyday eco-friendly stylish comfortable perfect durable affordable designed classic lightweight quality elegant compact premium luxury.', 'category': 'Home & Kitchen', 'price': 392, 'regular_price': 497, 'in_stock': 16},
            {'name': 'Bracelet', 'description': 'Portable high-performance modern crafted everyday affordable premium premium comfortable perfect durable everyday high-performance designed unique compact classic popular lightweight comfortable perfect stylish portable comfortable modern suitable popular.', 'category': 'Jewelry & Accessories', 'price': 174, 'regular_price': 343, 'in_stock': 18},
            {'name': 'Vacuum Cleaner', 'description': 'Eco-friendly suitable durable eco-friendly professional durable luxury quality innovative unique unique everyday professional essential essential exclusive modern.', 'category': 'Home & Kitchen', 'price': 384, 'regular_price': 390, 'in_stock': 7},
            {'name': 'Laptop', 'description': 'Versatile compact compact elegant lightweight versatile comfortable portable reliable affordable reliable portable lightweight everyday long-lasting suitable premium stylish eco-friendly eco-friendly.', 'category': 'Electronics', 'price': 465, 'regular_price': 477, 'in_stock': 8},
            {'name': 'Dumbbells', 'description': 'Reliable lightweight elegant luxury suitable crafted quality long-lasting crafted elegant comfortable innovative perfect professional compact popular versatile premium everyday lightweight eco-friendly comfortable professional luxury high-performance essential.', 'category': 'Sports & Fitness', 'price': 203, 'regular_price': 360, 'in_stock': 8},
            {'name': 'Jump Starter', 'description': 'Affordable elegant premium classic reliable stylish essential premium popular compact classic compact eco-friendly exclusive designed everyday affordable perfect comfortable suitable eco-friendly crafted modern everyday portable designed long-lasting lightweight luxury durable.', 'category': 'Automotive & Tools', 'price': 337, 'regular_price': 349, 'in_stock': 8},
            {'name': 'Tennis Racket', 'description': 'Quality reliable unique luxury professional comfortable classic affordable luxury essential reliable exclusive luxury.', 'category': 'Sports & Fitness', 'price': 250, 'regular_price': 285, 'in_stock': 16},
            {'name': 'Coffee Maker', 'description': 'Stylish long-lasting innovative suitable portable affordable elegant versatile durable modern high-performance professional unique long-lasting.', 'category': 'Home & Kitchen', 'price': 425, 'regular_price': 460, 'in_stock': 16},
            {'name': 'Moisturizer', 'description': 'Elegant high-performance stylish high-performance modern professional luxury trendy perfect premium classic.', 'category': 'Health & Beauty', 'price': 315, 'regular_price': 376, 'in_stock': 12},
            {'name': 'Coffee Maker', 'description': 'Modern elegant premium luxury quality everyday modern innovative essential trendy luxury portable popular stylish suitable affordable long-lasting luxury crafted comfortable affordable unique everyday essential luxury quality.', 'category': 'Home & Kitchen', 'price': 200, 'regular_price': 243, 'in_stock': 6},
            {'name': 'Bluetooth Speaker', 'description': 'Classic versatile affordable suitable exclusive trendy premium exclusive modern quality modern suitable lightweight comfortable long-lasting modern professional perfect crafted professional stylish compact lightweight perfect.', 'category': 'Electronics', 'price': 169, 'regular_price': 388, 'in_stock': 18},
            {'name': 'Wrench Set', 'description': 'Eco-friendly popular premium perfect designed essential elegant portable trendy unique exclusive high-performance affordable durable popular compact compact reliable quality luxury elegant crafted.', 'category': 'Automotive & Tools', 'price': 142, 'regular_price': 411, 'in_stock': 20},
            {'name': 'Necklace', 'description': 'Designed designed unique crafted luxury lightweight versatile affordable luxury premium comfortable professional quality innovative.', 'category': 'Jewelry & Accessories', 'price': 491, 'regular_price': 492, 'in_stock': 16},
            {'name': 'Shampoo', 'description': 'Quality everyday high-performance long-lasting premium designed perfect designed crafted elegant premium trendy elegant modern perfect eco-friendly innovative eco-friendly trendy high-performance quality.', 'category': 'Health & Beauty', 'price': 267, 'regular_price': 407, 'in_stock': 16},
            {'name': 'Microwave', 'description': 'Classic elegant professional essential modern innovative professional portable luxury classic innovative everyday high-performance stylish exclusive quality elegant elegant exclusive elegant.', 'category': 'Home & Kitchen', 'price': 231, 'regular_price': 383, 'in_stock': 17},
            {'name': 'Non-stick Pan', 'description': 'Unique eco-friendly elegant versatile versatile trendy classic quality designed elegant professional quality.', 'category': 'Home & Kitchen', 'price': 456, 'regular_price': 485, 'in_stock': 16},
            {'name': 'Earrings', 'description': 'Quality stylish eco-friendly suitable affordable affordable high-performance long-lasting portable professional trendy high-performance lightweight premium compact elegant affordable.', 'category': 'Jewelry & Accessories', 'price': 176, 'regular_price': 220, 'in_stock': 16},
            {'name': 'Pasta', 'description': 'Luxury perfect professional luxury everyday professional reliable reliable everyday designed long-lasting perfect stylish high-performance perfect compact luxury.', 'category': 'Groceries & Food', 'price': 122, 'regular_price': 296, 'in_stock': 16},
            {'name': 'Planner', 'description': 'Versatile lightweight affordable premium premium premium perfect modern premium popular affordable luxury compact elegant high-performance lightweight modern quality essential versatile classic long-lasting long-lasting elegant trendy designed premium popular popular modern.', 'category': 'Books & Stationery', 'price': 400, 'regular_price': 468, 'in_stock': 5},
            {'name': 'Wristwatch', 'description': 'Quality comfortable premium crafted innovative modern long-lasting durable quality trendy quality.', 'category': 'Jewelry & Accessories', 'price': 450, 'regular_price': 493, 'in_stock': 7},
            {'name': 'Non-stick Pan', 'description': 'Luxury unique unique durable compact crafted compact exclusive perfect long-lasting affordable essential compact eco-friendly everyday innovative portable designed trendy suitable.', 'category': 'Home & Kitchen', 'price': 178, 'regular_price': 313, 'in_stock': 18},
            {'name': 'T-shirt', 'description': 'Everyday popular classic crafted quality essential quality durable durable lightweight classic versatile professional durable portable modern luxury lightweight crafted suitable everyday suitable exclusive affordable suitable compact high-performance reliable everyday suitable.', 'category': 'Clothing & Fashion', 'price': 200, 'regular_price': 464, 'in_stock': 17},
            {'name': 'Dumbbells', 'description': 'Everyday stylish professional elegant professional suitable premium portable everyday professional reliable unique essential premium elegant professional long-lasting.', 'category': 'Sports & Fitness', 'price': 103, 'regular_price': 138, 'in_stock': 8},
            {'name': 'Necklace', 'description': 'Reliable designed long-lasting versatile premium premium durable elegant elegant reliable.', 'category': 'Jewelry & Accessories', 'price': 268, 'regular_price': 302, 'in_stock': 14},
            {'name': 'Dollhouse', 'description': 'Innovative luxury durable affordable lightweight eco-friendly long-lasting popular durable perfect.', 'category': 'Toys & Games', 'price': 349, 'regular_price': 397, 'in_stock': 18},
            {'name': 'Perfume', 'description': 'Modern trendy popular luxury compact perfect high-performance trendy compact designed designed compact modern affordable professional versatile essential popular popular stylish innovative durable unique durable everyday suitable innovative suitable comfortable eco-friendly.', 'category': 'Health & Beauty', 'price': 423, 'regular_price': 494, 'in_stock': 16},
            {'name': 'Textbook', 'description': 'Eco-friendly eco-friendly exclusive professional classic versatile portable long-lasting unique durable professional designed exclusive long-lasting durable professional trendy classic.', 'category': 'Books & Stationery', 'price': 499, 'regular_price': 499, 'in_stock': 17},
            {'name': 'Pasta', 'description': 'Suitable stylish essential essential long-lasting perfect versatile popular modern essential popular luxury.', 'category': 'Groceries & Food', 'price': 491, 'regular_price': 495, 'in_stock': 13},
            {'name': 'Smartwatch', 'description': 'Versatile portable suitable affordable stylish durable modern designed suitable modern professional affordable everyday reliable perfect lightweight eco-friendly versatile everyday everyday.', 'category': 'Electronics', 'price': 161, 'regular_price': 241, 'in_stock': 12},
            {'name': 'Notebook', 'description': 'Trendy crafted modern modern popular long-lasting lightweight high-performance eco-friendly crafted portable reliable quality stylish eco-friendly compact unique innovative high-performance eco-friendly lightweight modern popular stylish lightweight unique popular designed.', 'category': 'Books & Stationery', 'price': 381, 'regular_price': 494, 'in_stock': 13},
            {'name': 'Car Vacuum', 'description': 'High-performance popular everyday trendy innovative long-lasting trendy quality comfortable popular lightweight.', 'category': 'Automotive & Tools', 'price': 302, 'regular_price': 484, 'in_stock': 13},
            {'name': 'Textbook', 'description': 'High-performance lightweight luxury affordable exclusive designed essential quality premium crafted high-performance innovative exclusive stylish crafted essential lightweight crafted.', 'category': 'Books & Stationery', 'price': 139, 'regular_price': 442, 'in_stock': 18},
            {'name': 'Sneakers', 'description': 'Elegant modern compact popular exclusive classic lightweight compact crafted luxury premium comfortable unique popular versatile reliable elegant versatile everyday professional reliable reliable designed stylish comfortable.', 'category': 'Clothing & Fashion', 'price': 350, 'regular_price': 418, 'in_stock': 15},
            {'name': 'Cereal', 'description': 'Reliable eco-friendly suitable premium unique quality versatile affordable modern unique trendy portable suitable modern compact suitable comfortable suitable reliable elegant.', 'category': 'Groceries & Food', 'price': 151, 'regular_price': 182, 'in_stock': 9},
            {'name': 'Tennis Racket', 'description': 'Premium eco-friendly high-performance modern designed versatile popular comfortable affordable premium luxury stylish professional lightweight everyday exclusive.', 'category': 'Sports & Fitness', 'price': 245, 'regular_price': 258, 'in_stock': 19},
            {'name': 'Lipstick', 'description': 'Professional compact crafted premium suitable comfortable comfortable lightweight suitable everyday comfortable exclusive long-lasting premium perfect premium eco-friendly versatile exclusive modern professional comfortable modern trendy elegant eco-friendly compact professional lightweight.', 'category': 'Health & Beauty', 'price': 142, 'regular_price': 449, 'in_stock': 17},
            {'name': 'Jacket', 'description': 'Luxury classic high-performance elegant popular unique quality everyday trendy versatile designed compact elegant long-lasting.', 'category': 'Clothing & Fashion', 'price': 441, 'regular_price': 493, 'in_stock': 19},
            {'name': 'Cereal', 'description': 'Suitable innovative stylish lightweight unique unique trendy suitable affordable classic long-lasting perfect everyday eco-friendly.', 'category': 'Groceries & Food', 'price': 307, 'regular_price': 328, 'in_stock': 8},
            {'name': 'Bracelet', 'description': 'Long-lasting classic durable long-lasting premium elegant reliable luxury exclusive lightweight long-lasting everyday exclusive high-performance innovative designed unique modern everyday stylish classic stylish eco-friendly professional portable comfortable long-lasting luxury everyday.', 'category': 'Jewelry & Accessories', 'price': 192, 'regular_price': 486, 'in_stock': 19},
            {'name': 'Cereal', 'description': 'Professional lightweight reliable affordable suitable compact compact crafted portable portable trendy.', 'category': 'Groceries & Food', 'price': 272, 'regular_price': 305, 'in_stock': 11},
            {'name': 'Blender', 'description': 'Designed lightweight exclusive elegant professional everyday elegant quality versatile portable lightweight comfortable trendy popular.', 'category': 'Home & Kitchen', 'price': 135, 'regular_price': 264, 'in_stock': 16},
            {'name': 'Tire Pump', 'description': 'Suitable premium trendy long-lasting innovative exclusive reliable compact reliable quality versatile lightweight suitable perfect versatile everyday comfortable suitable trendy long-lasting classic everyday suitable crafted unique comfortable popular designed classic unique.', 'category': 'Automotive & Tools', 'price': 317, 'regular_price': 433, 'in_stock': 6},
            {'name': 'Tennis Racket', 'description': 'Innovative durable reliable crafted innovative perfect professional classic lightweight popular affordable elegant portable elegant.', 'category': 'Sports & Fitness', 'price': 137, 'regular_price': 180, 'in_stock': 16},
            {'name': 'Planner', 'description': 'Popular designed elegant high-performance modern reliable suitable professional luxury versatile innovative designed classic quality essential popular classic professional premium elegant quality professional essential.', 'category': 'Books & Stationery', 'price': 175, 'regular_price': 275, 'in_stock': 15},
            {'name': 'Cereal', 'description': 'Crafted modern compact modern modern eco-friendly long-lasting designed classic comfortable affordable exclusive long-lasting trendy innovative compact suitable classic everyday.', 'category': 'Groceries & Food', 'price': 217, 'regular_price': 484, 'in_stock': 11},
            {'name': 'Sneakers', 'description': 'Lightweight designed classic popular exclusive luxury essential exclusive reliable elegant crafted perfect unique professional eco-friendly portable.', 'category': 'Clothing & Fashion', 'price': 394, 'regular_price': 491, 'in_stock': 18},
            {'name': 'Wristwatch', 'description': 'Modern luxury stylish reliable eco-friendly quality suitable elegant professional portable everyday innovative high-performance trendy durable premium affordable innovative perfect classic crafted innovative everyday comfortable perfect suitable.', 'category': 'Jewelry & Accessories', 'price': 346, 'regular_price': 437, 'in_stock': 20},
            {'name': 'Perfume', 'description': 'Crafted elegant unique portable popular quality compact innovative luxury stylish modern innovative luxury trendy modern.', 'category': 'Health & Beauty', 'price': 389, 'regular_price': 413, 'in_stock': 18},
            {'name': 'Jacket', 'description': 'Professional popular innovative quality essential premium innovative high-performance portable designed portable suitable affordable.', 'category': 'Clothing & Fashion', 'price': 163, 'regular_price': 188, 'in_stock': 18},
        ]

        product_categories = [
            "Electronics",
            "Clothing & Fashion",
            "Home & Kitchen",
            "Health & Beauty",
            "Sports & Fitness",
            "Books & Stationery",
            "Toys & Games",
            "Automotive & Tools",
            "Jewelry & Accessories",
            "Groceries & Food"
        ]

        def create_product_variant(self, variant_name, product):
            for variant in variant_name:
                ProductVariant.objects.create(product=product, name=variant)
                



        for each_product in all_products:
            categories_with_variant = [
                "Clothing & Fashion",
                "Sports & Fitness",
                "Toys & Games",
                "Automotive & Tools",
                "Jewelry & Accessories",
            ]
            category , created = Category.objects.get_or_create(name=each_product['category'])
            product = Product(name=each_product['name'], description=each_product['description'], category=category, price=each_product['price'], regular_price=each_product['regular_price'], in_stock=each_product['in_stock'])
            product.save()
            if each_product['category'] in categories_with_variant:
                variant_name = ['color', 'size']
                create_product_variant(self, variant_name, product)
                
            print(f'category: {category}     product: {product} \n\n')

        # print(f'all category: {all_category} \n')

        # print(f'category: {category} \n')
        # print(f'created: {created} \n')




        # Product.objects.create(name='', )
        




