# Generated by Django 4.2.23 on 2025-08-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usertype',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('vendor', 'vendor')], default=None, max_length=255, null=True),
        ),
    ]
